# Site settings
title: Kindred Spirits
email: jena@kindredspirits.io
description: > # this means to ignore newlines until "baseurl:"
Kindred Spirits is a blog run by Jena Donlin about the books she reads and the type of professional she wants to be.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kindredspirits.io" # the base hostname & protocol for your site
twitter_username: donlinje
github_username:  jenakalif

# Build settings
markdown: kramdown
